/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.demo.domain;


import cn.vertxup.demo.domain.tables.XTabular;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbEternal extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DB_ETERNAL</code>
     */
    public static final DbEternal DB_ETERNAL = new DbEternal();

    /**
     * The table <code>DB_ETERNAL.X_TABULAR</code>.
     */
    public final XTabular X_TABULAR = XTabular.X_TABULAR;

    /**
     * No further instances allowed
     */
    private DbEternal() {
        super("DB_ETERNAL", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            XTabular.X_TABULAR
        );
    }
}
