/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.demo.domain;


import cn.vertxup.demo.domain.tables.XTabular;


/**
 * Convenience access to all tables in DB_ETERNAL.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DB_ETERNAL.X_TABULAR</code>.
     */
    public static final XTabular X_TABULAR = XTabular.X_TABULAR;
}
