/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.demo.domain;


import cn.vertxup.demo.domain.tables.XTabular;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbEternal extends SchemaImpl {

    private static final long serialVersionUID = 792051652;

    /**
     * The reference instance of <code>DB_ETERNAL</code>
     */
    public static final DbEternal DB_ETERNAL = new DbEternal();

    /**
     * The table <code>DB_ETERNAL.X_TABULAR</code>.
     */
    public final XTabular X_TABULAR = cn.vertxup.demo.domain.tables.XTabular.X_TABULAR;

    /**
     * No further instances allowed
     */
    private DbEternal() {
        super("DB_ETERNAL", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            XTabular.X_TABULAR);
    }
}
