/*
 * This file is generated by jOOQ.
 */
package cn.vertxup.demo.domain;


import cn.vertxup.demo.domain.tables.XTabular;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in DB_ETERNAL.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index X_TABULAR_IDXM_X_TABULAR_APP_ID_TYPE_ACTIVE = Internal.createIndex(DSL.name("IDXM_X_TABULAR_APP_ID_TYPE_ACTIVE"), XTabular.X_TABULAR, new OrderField[] { XTabular.X_TABULAR.APP_ID, XTabular.X_TABULAR.TYPE, XTabular.X_TABULAR.ACTIVE }, false);
    public static final Index X_TABULAR_IDXM_X_TABULAR_SIGMA_TYPE_ACTIVE = Internal.createIndex(DSL.name("IDXM_X_TABULAR_SIGMA_TYPE_ACTIVE"), XTabular.X_TABULAR, new OrderField[] { XTabular.X_TABULAR.SIGMA, XTabular.X_TABULAR.TYPE, XTabular.X_TABULAR.ACTIVE }, false);
}
