/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.demo.domain;


import cn.vertxup.demo.domain.tables.XTabular;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>DB_ETERNAL</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index X_TABULAR_APP_ID = Indexes0.X_TABULAR_APP_ID;
    public static final Index X_TABULAR_IDXM_X_TABULAR_APP_ID_TYPE_ACTIVE = Indexes0.X_TABULAR_IDXM_X_TABULAR_APP_ID_TYPE_ACTIVE;
    public static final Index X_TABULAR_IDXM_X_TABULAR_SIGMA_TYPE_ACTIVE = Indexes0.X_TABULAR_IDXM_X_TABULAR_SIGMA_TYPE_ACTIVE;
    public static final Index X_TABULAR_PRIMARY = Indexes0.X_TABULAR_PRIMARY;
    public static final Index X_TABULAR_SIGMA = Indexes0.X_TABULAR_SIGMA;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index X_TABULAR_APP_ID = Internal.createIndex("APP_ID", XTabular.X_TABULAR, new OrderField[] { XTabular.X_TABULAR.APP_ID, XTabular.X_TABULAR.TYPE, XTabular.X_TABULAR.CODE }, true);
        public static Index X_TABULAR_IDXM_X_TABULAR_APP_ID_TYPE_ACTIVE = Internal.createIndex("IDXM_X_TABULAR_APP_ID_TYPE_ACTIVE", XTabular.X_TABULAR, new OrderField[] { XTabular.X_TABULAR.APP_ID, XTabular.X_TABULAR.TYPE, XTabular.X_TABULAR.ACTIVE }, false);
        public static Index X_TABULAR_IDXM_X_TABULAR_SIGMA_TYPE_ACTIVE = Internal.createIndex("IDXM_X_TABULAR_SIGMA_TYPE_ACTIVE", XTabular.X_TABULAR, new OrderField[] { XTabular.X_TABULAR.SIGMA, XTabular.X_TABULAR.TYPE, XTabular.X_TABULAR.ACTIVE }, false);
        public static Index X_TABULAR_PRIMARY = Internal.createIndex("PRIMARY", XTabular.X_TABULAR, new OrderField[] { XTabular.X_TABULAR.KEY }, true);
        public static Index X_TABULAR_SIGMA = Internal.createIndex("SIGMA", XTabular.X_TABULAR, new OrderField[] { XTabular.X_TABULAR.SIGMA, XTabular.X_TABULAR.TYPE, XTabular.X_TABULAR.CODE }, true);
    }
}
