/*
 * This file is generated by jOOQ.
*/
package cn.vertxup.demo.domain;


import cn.vertxup.demo.domain.tables.XTabular;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in DB_ETERNAL
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DB_ETERNAL.X_TABULAR</code>.
     */
    public static final XTabular X_TABULAR = cn.vertxup.demo.domain.tables.XTabular.X_TABULAR;
}
